config/routes.rb
Musicapp::Application.routes.draw do
  resources :users, only: [:create, :new, :edit, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true
  validates :band_id, presence: true
  validates :recording,
            inclusion: { in: %w(Studio Live), allow_nil: true}

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :single, inclusion: { in: %w(Bonus Regular), allow_nil: true}

  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, presence: true
  validates :session_token, presence: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user: nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    @password=password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
    def ensure_session_token
      self.session_token ||= self.class.generate_session_token
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    album = Album.new(album_params)
    if album.save
      flash[:notice] = "Album created successfully."
      redirect_to album_url(album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :new
    end
  end

  def new
    @album = Album.new(band_id: params[:band_id])
  end

  def edit
    @album = Album.find_by_id(params[:id])
    @band_name = @album.band.name
    @bands = Band.all
  end

  def show
    @album = Album.find_by_id(params[:id])
  end

  def update
    @album = Album.find_by_id(params[:id])
    @album.update(album_params)
    redirect_to album_url(@album)
  end

  def destroy
    album = Album.find_by_id(params[:id])
    band = album.band
    album.destroy!
    flash[:notice] = "Album has been deleted"
    redirect_to band_url(band)
  end

  private
    def album_params
      params.require(:album).permit(:band_id, :title, :recording)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(
                session_token: session[:session_token])
  end

  def logged_in?
    !session[:session_token].nil?
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def create
    band = Band.new(band_params)
    if band.save
      flash[:notice] = "Band created successfully."
      redirect_to band_url(band)
    else
      flask.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
  end

  def edit
    @band = Band.find_by_id(params[:id])
  end

  def show
    @band = Band.find_by_id(params[:id])
  end

  def update
    @band = Band.find_by_id(params[:id])
    @band.update(band_params)
    redirect_to band_url(@band)
  end

  def destroy
    band = Band.find_by_id(params[:id])
    band.destroy!
    flash[:notice] = "Band has been deleted"
    redirect_to bands_url
  end

  private
    def band_params
      params.require(:band).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to user_url(current_user)
    end
  end

  def create
    user = User.find_by_credentials(
                params[:user][:email],
                params[:user][:password]
                )

    if user
      user.reset_session_token!
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end

  end

  def destroy
    logout!
    redirect_to new_session_url
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to user_url(current_user)
    else
      @user = User.new
    end
  end

  def edit
    @user = User.find_by(params[:id])
  end

  def show
    @user = User.find_by(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = "You have successfully signed up."
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :email)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def csrf_token
    <<-HTML.html_safe
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% if !album.nil? && album.persisted? %>
<% str = "Change" %>
<form action="<%= album_url(album) %>" method="post">
  <%= csrf_token %>
  <input type="hidden" name="_method" value="PATCH">
  <label>Band</label>
  <select name="album[band_id]">
    <% bands.each do |band| %>
      <option value="<%= band.id %>"
         <%= "selected" if album.band_id == band.id %>>
         <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>
  <label>Title</label>
  <input type="text" name="album[title]" value="<%= album.title %>">
  <br>
  <label>Record Setting</label>
  <br>
  <input type="radio"
         name="album[recording]"
         value="Studio"
         <%= "checked" if album.recording == "Studio" %>>Studio<br>
  <input type="radio"
         name="album[recording]"
         value="Live"
         <%= "checked" if album.recording == "Live" %>>Live
  <br>
<% else %>
<% str = "Create" %>
<form action="<%= albums_url %>" method="post">
<%= csrf_token %>
  <input type="hidden"
      name="album[band_id]"
      value="<%= album.band_id %>">

  <label>Title</label>
  <input type="text" name="album[title]">
  <br>
  <label>Record Setting</label>
  <br>
  <input type="radio"
         name="album[recording]"
         value="Studio">Studio<br>
  <input type="radio"
         name="album[recording]"
         value="Live">Live<br>
<% end %>
  <button><%= str %> Album</button>
</form>

app/views/albums/edit.html.erb
<h1>Edit the album: <%= @album.title %></h1>
<h3>by <%= @band_name %></h3>

<%= render partial: "form", locals: { bands: @bands, album: @album } %>

app/views/albums/new.html.erb
<h1>Create a new Album</h1>

<%= render partial: "form", locals: { bands: @bands, album: @album } %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<h3>Tracks in this album</h3>
<ol>
<% @album.tracks.each do |track| %>
  <li><a href="<%= track_url(track) %>"><%= track.song %></a></li>
<% end %>
</ol>
<footer>
<a href="<%= edit_album_url(@album) %>">Edit</a>
</footer>

app/views/bands/_form.html.erb
<% if band.persisted? %>
<% str = "Change name of" %>
<form action="<%= band_url(band) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
<% else %>
<% str = "Create" %>
<form action="<%= bands_url %>" method="post">
<% end %>
<%= csrf_token %>
  <label>Name</label>
  <input type="text" name="band[name]" value="<%= band.name %>">
  <br>
  <button><%= str %> Band</button>
</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render partial: "form", locals: { band: @band } %>

app/views/bands/index.html.erb
<h1>All Rocking Bands</h1>
<ul>
<% @bands.each do |band| %>
  <li>
    <a href="<%= band_url(band) %>"><%= band.name %></a>
    <%= button_to "Delete", band_url(band), method: :delete %>
  </li>
<% end %>
</ul>

app/views/bands/new.html.erb
<h1>Create a Band</h1>

<%= render partial: "form", locals: { band: @band } %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3>Albums</h3>
<ol>
<% @band.albums.each do |album| %>
  <li>
    <a href="<%= album_url(album) %>"><%= album.title %></a>
    <%= button_to "Delete", album_url(album), method: :delete %>
  </li>
<% end %>
</ol>
<footer>
<a href="<%= edit_band_url(@band) %>">Edit</a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if logged_in? %>
  <%= button_to "Log out", session_url, method: :delete %><br>
<% else %>
  <%= link_to "Log in", new_session_url %><br>
<% end %>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="POST">
  <%= csrf_token %>
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">
  <br>
  <label for="password">New Password</label>
  <input type="password" name="user[password]" id="password">
  <br>
  <button>Sign up</button>
</form>

app/views/users/show.html.erb
<h1>Hello, <%= @user.email %></h1>